// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :one
UPDATE users
SET is_banned = true
WHERE id = $1
RETURNING id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned
`

func (q *Queries) BanUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, banUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const getActiveUsersCount = `-- name: GetActiveUsersCount :one
SELECT COUNT(DISTINCT user_id)::INT
FROM submissions
`

func (q *Queries) GetActiveUsersCount(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getActiveUsersCount)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned
FROM users
ORDER BY name ASC, id ASC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.RegNo,
			&i.Role,
			&i.RoundQualified,
			&i.GoogleID,
			&i.Balance,
			&i.Score,
			&i.Name,
			&i.IsBanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBannedUsersCount = `-- name: GetBannedUsersCount :one
SELECT COUNT(*)::INT
FROM users
WHERE is_banned = true
`

func (q *Queries) GetBannedUsersCount(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getBannedUsersCount)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getLanguageDistribution = `-- name: GetLanguageDistribution :many
SELECT language_id, COUNT(*)::INT AS submission_count
FROM submissions
GROUP BY language_id
ORDER BY submission_count DESC
`

type GetLanguageDistributionRow struct {
	LanguageID      int32
	SubmissionCount int32
}

func (q *Queries) GetLanguageDistribution(ctx context.Context) ([]GetLanguageDistributionRow, error) {
	rows, err := q.db.Query(ctx, getLanguageDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLanguageDistributionRow
	for rows.Next() {
		var i GetLanguageDistributionRow
		if err := rows.Scan(&i.LanguageID, &i.SubmissionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardData = `-- name: GetLeaderboardData :many
SELECT 
    u.id, 
    u.name, 
    u.email, 
    u.reg_no, 
    u.score,
    u.round_qualified,
    u.is_banned,
    COALESCE(SUM(s.runtime), 0)::DECIMAL AS total_runtime,
    MAX(s.submission_time)::TIMESTAMPTZ AS last_submission_time,
    COUNT(s.id)::INT AS total_submissions,
    COUNT(DISTINCT CASE WHEN LOWER(s.status) = 'success' THEN s.question_id END)::INT AS solved_count
FROM users u
LEFT JOIN submissions s ON s.user_id = u.id AND LOWER(s.status) = 'success'
GROUP BY u.id, u.name, u.email, u.reg_no, u.score, u.round_qualified, u.is_banned
ORDER BY u.score DESC, total_runtime ASC, last_submission_time ASC NULLS LAST, u.name ASC
`

type GetLeaderboardDataRow struct {
	ID                 uuid.UUID
	Name               string
	Email              string
	RegNo              string
	Score              pgtype.Numeric
	RoundQualified     int32
	IsBanned           bool
	TotalRuntime       pgtype.Numeric
	LastSubmissionTime pgtype.Timestamptz
	TotalSubmissions   int32
	SolvedCount        int32
}

func (q *Queries) GetLeaderboardData(ctx context.Context) ([]GetLeaderboardDataRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboardData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardDataRow
	for rows.Next() {
		var i GetLeaderboardDataRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.RegNo,
			&i.Score,
			&i.RoundQualified,
			&i.IsBanned,
			&i.TotalRuntime,
			&i.LastSubmissionTime,
			&i.TotalSubmissions,
			&i.SolvedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentSubmissionsCount = `-- name: GetRecentSubmissionsCount :one
SELECT COUNT(*)::INT
FROM submissions
WHERE submission_time >= $1
`

func (q *Queries) GetRecentSubmissionsCount(ctx context.Context, submissionTime pgtype.Timestamptz) (int32, error) {
	row := q.db.QueryRow(ctx, getRecentSubmissionsCount, submissionTime)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getSubmissionsAnalytics = `-- name: GetSubmissionsAnalytics :one
SELECT 
    COUNT(*)::INT AS total_submissions,
    COUNT(CASE WHEN LOWER(status) = 'success' THEN 1 END)::INT AS successful_submissions,
    COUNT(CASE WHEN LOWER(status) != 'success' OR status IS NULL THEN 1 END)::INT AS failed_submissions,
    COALESCE(SUM(testcases_passed), 0)::BIGINT AS total_testcases_passed,
    COALESCE(SUM(testcases_failed), 0)::BIGINT AS total_testcases_failed
FROM submissions
`

type GetSubmissionsAnalyticsRow struct {
	TotalSubmissions      int32
	SuccessfulSubmissions int32
	FailedSubmissions     int32
	TotalTestcasesPassed  int64
	TotalTestcasesFailed  int64
}

func (q *Queries) GetSubmissionsAnalytics(ctx context.Context) (GetSubmissionsAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionsAnalytics)
	var i GetSubmissionsAnalyticsRow
	err := row.Scan(
		&i.TotalSubmissions,
		&i.SuccessfulSubmissions,
		&i.FailedSubmissions,
		&i.TotalTestcasesPassed,
		&i.TotalTestcasesFailed,
	)
	return i, err
}

const getTotalUsersCount = `-- name: GetTotalUsersCount :one
SELECT COUNT(*)::INT
FROM users
`

func (q *Queries) GetTotalUsersCount(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getTotalUsersCount)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserSubmissions = `-- name: GetUserSubmissions :many
SELECT s.id, s.question_id, s.testcases_passed, s.testcases_failed, s.runtime, s.submission_time, s.source_code, s.language_id, s.description, s.memory, s.user_id, s.status,
       q.title AS question_title, q.round AS question_round
FROM submissions s
JOIN questions q ON q.id = s.question_id
WHERE s.user_id = $1
ORDER BY s.submission_time DESC, s.id DESC
`

type GetUserSubmissionsRow struct {
	ID              uuid.UUID
	QuestionID      uuid.UUID
	TestcasesPassed *int32
	TestcasesFailed *int32
	Runtime         pgtype.Numeric
	SubmissionTime  pgtype.Timestamptz
	SourceCode      string
	LanguageID      int32
	Description     *string
	Memory          pgtype.Numeric
	UserID          uuid.UUID
	Status          *string
	QuestionTitle   string
	QuestionRound   int32
}

func (q *Queries) GetUserSubmissions(ctx context.Context, userID uuid.UUID) ([]GetUserSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserSubmissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSubmissionsRow
	for rows.Next() {
		var i GetUserSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.TestcasesPassed,
			&i.TestcasesFailed,
			&i.Runtime,
			&i.SubmissionTime,
			&i.SourceCode,
			&i.LanguageID,
			&i.Description,
			&i.Memory,
			&i.UserID,
			&i.Status,
			&i.QuestionTitle,
			&i.QuestionRound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementUserRound = `-- name: IncrementUserRound :one
UPDATE users
SET round_qualified = round_qualified + 1
WHERE id = $1
RETURNING id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned
`

func (q *Queries) IncrementUserRound(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, incrementUserRound, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const unbanUser = `-- name: UnbanUser :one
UPDATE users
SET is_banned = false
WHERE id = $1
RETURNING id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned
`

func (q *Queries) UnbanUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, unbanUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2
WHERE id = $1
RETURNING id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const upgradeAllUsersRound = `-- name: UpgradeAllUsersRound :execrows
UPDATE users
SET round_qualified = $1
WHERE is_banned = false AND round_qualified < $1
`

func (q *Queries) UpgradeAllUsersRound(ctx context.Context, roundQualified int32) (int64, error) {
	result, err := q.db.Exec(ctx, upgradeAllUsersRound, roundQualified)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upgradeUserRound = `-- name: UpgradeUserRound :one
UPDATE users
SET round_qualified = $2
WHERE id = $1
RETURNING id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned
`

type UpgradeUserRoundParams struct {
	ID             uuid.UUID
	RoundQualified int32
}

func (q *Queries) UpgradeUserRound(ctx context.Context, arg UpgradeUserRoundParams) (User, error) {
	row := q.db.QueryRow(ctx, upgradeUserRound, arg.ID, arg.RoundQualified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}
