// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO attempts(
    id,
    user_id,
    question_id,
    status,
    is_buy_in_paid
)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, question_id, status, is_buy_in_paid, attempted_at, answered_at
`

type CreateAttemptParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	QuestionID  uuid.UUID
	Status      string
	IsBuyInPaid bool
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.ID,
		arg.UserID,
		arg.QuestionID,
		arg.Status,
		arg.IsBuyInPaid,
	)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Status,
		&i.IsBuyInPaid,
		&i.AttemptedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const ensureAttempt = `-- name: EnsureAttempt :exec
INSERT INTO attempts (id, user_id, question_id, status, is_buy_in_paid)
VALUES ($1, $2, $3, 'bought', false)
ON CONFLICT ON CONSTRAINT uq_attempts_user_question DO NOTHING
`

type EnsureAttemptParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	QuestionID uuid.UUID
}

func (q *Queries) EnsureAttempt(ctx context.Context, arg EnsureAttemptParams) error {
	_, err := q.db.Exec(ctx, ensureAttempt, arg.ID, arg.UserID, arg.QuestionID)
	return err
}

const getAttemptForUpdate = `-- name: GetAttemptForUpdate :one
SELECT id, user_id, question_id, status, is_buy_in_paid, attempted_at, answered_at
FROM attempts
WHERE user_id = $1
  AND question_id = $2
FOR UPDATE
`

type GetAttemptForUpdateParams struct {
	UserID     uuid.UUID
	QuestionID uuid.UUID
}

func (q *Queries) GetAttemptForUpdate(ctx context.Context, arg GetAttemptForUpdateParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttemptForUpdate, arg.UserID, arg.QuestionID)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.QuestionID,
		&i.Status,
		&i.IsBuyInPaid,
		&i.AttemptedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const getQuestionBuyIn = `-- name: GetQuestionBuyIn :one
SELECT buy_in
FROM questions
WHERE id = $1
`

func (q *Queries) GetQuestionBuyIn(ctx context.Context, id uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getQuestionBuyIn, id)
	var buy_in pgtype.Numeric
	err := row.Scan(&buy_in)
	return buy_in, err
}

const getUserBalanceForUpdate = `-- name: GetUserBalanceForUpdate :one
SELECT balance
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetUserBalanceForUpdate(ctx context.Context, id uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getUserBalanceForUpdate, id)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const updateUserBalance = `-- name: UpdateUserBalance :exec
UPDATE users
SET balance = $1
WHERE id = $2
`

type UpdateUserBalanceParams struct {
	Balance pgtype.Numeric
	ID      uuid.UUID
}

func (q *Queries) UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error {
	_, err := q.db.Exec(ctx, updateUserBalance, arg.Balance, arg.ID)
	return err
}
