// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserFromGoogle = `-- name: CreateUserFromGoogle :one
INSERT INTO users (id, email, reg_no, role, name, google_id, balance)
VALUES ($1, $2, $3, 'user', $4, $5, $6)
ON CONFLICT DO NOTHING
RETURNING id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned
`

type CreateUserFromGoogleParams struct {
	ID       uuid.UUID
	Email    string
	RegNo    string
	Name     string
	GoogleID *string
	Balance  pgtype.Numeric
}

func (q *Queries) CreateUserFromGoogle(ctx context.Context, arg CreateUserFromGoogleParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserFromGoogle,
		arg.ID,
		arg.Email,
		arg.RegNo,
		arg.Name,
		arg.GoogleID,
		arg.Balance,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned FROM users WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const linkGoogleID = `-- name: LinkGoogleID :one
UPDATE users SET google_id = $2 WHERE id = $1 AND google_id IS NULL
RETURNING id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned
`

type LinkGoogleIDParams struct {
	ID       uuid.UUID
	GoogleID *string
}

func (q *Queries) LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) (User, error) {
	row := q.db.QueryRow(ctx, linkGoogleID, arg.ID, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}
