// Code generated by sqlc. DO NOT EDIT.
// source: auth.sql

package sqlc

import (
	"context"
	"github.com/google/uuid"
)

const userColumns = "id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned"

type CreateGoogleUserParams struct {
	ID                                 uuid.UUID
	Email, RegNo, Role, GoogleID, Name string
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, "INSERT INTO users (id, email, reg_no, role, google_id, name) VALUES ($1, $2, $3, $4, $5, $6) RETURNING "+userColumns, arg.ID, arg.Email, arg.RegNo, arg.Role, arg.GoogleID, arg.Name)
	return scanUser(row)
}

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	return scanUser(q.db.QueryRow(ctx, "SELECT "+userColumns+" FROM users WHERE google_id = $1", googleID))
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	return scanUser(q.db.QueryRow(ctx, "SELECT "+userColumns+" FROM users WHERE id = $1", id))
}

func scanUser(row interface{ Scan(...interface{}) error }) (User, error) {
	var user User
	err := row.Scan(&user.ID, &user.Email, &user.RegNo, &user.Role, &user.RoundQualified, &user.GoogleID, &user.Balance, &user.Score, &user.Name, &user.IsBanned)
	return user, err
}
