// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createGoogleUser = `-- name: CreateGoogleUser :one
INSERT INTO users (id, email, reg_no, role, google_id, name) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned
`

type CreateGoogleUserParams struct {
	ID       uuid.UUID
	Email    string
	RegNo    string
	Role     string
	GoogleID *string
	Name     string
}

func (q *Queries) CreateGoogleUser(ctx context.Context, arg CreateGoogleUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createGoogleUser,
		arg.ID,
		arg.Email,
		arg.RegNo,
		arg.Role,
		arg.GoogleID,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned FROM users WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}

const linkGoogleID = `-- name: LinkGoogleID :one
UPDATE users SET google_id = $2 WHERE id = $1 AND google_id IS NULL
RETURNING id, email, reg_no, role, round_qualified, google_id, balance, score, name, is_banned
`

type LinkGoogleIDParams struct {
	ID       uuid.UUID
	GoogleID *string
}

func (q *Queries) LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) (User, error) {
	row := q.db.QueryRow(ctx, linkGoogleID, arg.ID, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.RegNo,
		&i.Role,
		&i.RoundQualified,
		&i.GoogleID,
		&i.Balance,
		&i.Score,
		&i.Name,
		&i.IsBanned,
	)
	return i, err
}
