// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listDashboardQuestions = `-- name: ListDashboardQuestions :many
SELECT q.id, q.title, q.points, q.round,
       COALESCE(a.status, 'available') AS attempt_status
FROM questions q
JOIN users u ON u.id = $1
LEFT JOIN attempts a ON a.question_id = q.id AND a.user_id = u.id
WHERE q.round = u.round_qualified
ORDER BY q.round ASC, q.title ASC, q.id ASC
`

type ListDashboardQuestionsRow struct {
	ID            uuid.UUID
	Title         string
	Points        int32
	Round         int32
	AttemptStatus string
}

func (q *Queries) ListDashboardQuestions(ctx context.Context, id uuid.UUID) ([]ListDashboardQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardQuestions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDashboardQuestionsRow
	for rows.Next() {
		var i ListDashboardQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Points,
			&i.Round,
			&i.AttemptStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
