// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getDashboardQuestions = `-- name: GetDashboardQuestions :many
SELECT 
    q.id,
    q.title,
    q.points,
    q.round,
    COALESCE(a.status, 'available')::text AS attempt_status
FROM questions q
JOIN users u ON u.id = $1
LEFT JOIN attempts a ON a.question_id = q.id AND a.user_id = u.id
WHERE q.round = u.round_qualified
ORDER BY q.title ASC, q.id ASC
`

type GetDashboardQuestionsRow struct {
	ID            uuid.UUID
	Title         string
	Points        int32
	Round         int32
	AttemptStatus string
}

func (q *Queries) GetDashboardQuestions(ctx context.Context, id uuid.UUID) ([]GetDashboardQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getDashboardQuestions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardQuestionsRow
	for rows.Next() {
		var i GetDashboardQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Points,
			&i.Round,
			&i.AttemptStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardRoundStats = `-- name: GetDashboardRoundStats :many
SELECT 
    q.round,
    COUNT(CASE WHEN a.status = 'answered' THEN 1 END)::int AS questions_completed,
    COUNT(CASE WHEN a.status = 'bought' OR (q.round = 1 AND (a.status IS NULL OR a.status = 'available')) THEN 1 END)::int AS questions_incomplete,
    COALESCE(SUM(CASE WHEN a.status = 'answered' THEN q.points ELSE 0 END), 0)::int AS round_score
FROM questions q
JOIN users u ON u.id = $1
LEFT JOIN attempts a ON a.question_id = q.id AND a.user_id = u.id
GROUP BY q.round
ORDER BY q.round ASC
`

type GetDashboardRoundStatsRow struct {
	Round               int32
	QuestionsCompleted  int32
	QuestionsIncomplete int32
	RoundScore          int32
}

func (q *Queries) GetDashboardRoundStats(ctx context.Context, id uuid.UUID) ([]GetDashboardRoundStatsRow, error) {
	rows, err := q.db.Query(ctx, getDashboardRoundStats, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardRoundStatsRow
	for rows.Next() {
		var i GetDashboardRoundStatsRow
		if err := rows.Scan(
			&i.Round,
			&i.QuestionsCompleted,
			&i.QuestionsIncomplete,
			&i.RoundScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
