// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attempt struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	QuestionID  uuid.UUID
	Status      string
	IsBuyInPaid bool
	AttemptedAt pgtype.Timestamptz
	AnsweredAt  pgtype.Timestamptz
}

type Question struct {
	ID               uuid.UUID
	Description      string
	Title            string
	QType            string
	InputFormat      []string
	BuyIn            pgtype.Numeric
	Reward           pgtype.Numeric
	Points           int32
	Round            int32
	Constraints      []string
	OutputFormat     []string
	SampleTestInput  []string
	SampleTestOutput []string
	Explanation      []string
	BountyActive     bool
}

type Submission struct {
	ID              uuid.UUID
	QuestionID      uuid.UUID
	TestcasesPassed *int32
	TestcasesFailed *int32
	Runtime         pgtype.Numeric
	SubmissionTime  pgtype.Timestamptz
	SourceCode      string
	LanguageID      int32
	Description     *string
	Memory          pgtype.Numeric
	UserID          uuid.UUID
	Status          *string
}

type SubmissionResult struct {
	ID            uuid.UUID
	TestcaseID    pgtype.UUID
	SubmissionID  uuid.UUID
	Runtime       pgtype.Numeric
	Memory        pgtype.Numeric
	PointsAwarded int32
	Status        string
	Description   *string
}

type Testcase struct {
	ID             uuid.UUID
	ExpectedOutput string
	Memory         pgtype.Numeric
	Input          string
	Hidden         bool
	Runtime        pgtype.Numeric
	QuestionID     uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Email          string
	RegNo          string
	Role           string
	RoundQualified int32
	GoogleID       *string
	Balance        pgtype.Numeric
	Score          pgtype.Numeric
	Name           string
	IsBanned       bool
}

type VisualBlock struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Content    string
}

type VisualSolution struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Solution   []uuid.UUID
	Points     pgtype.Numeric
}
