// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error)
	CreateVisualSubmission(ctx context.Context, arg CreateVisualSubmissionParams) (Submission, error)
	GetAttemptForUpdate(ctx context.Context, arg GetAttemptForUpdateParams) (Attempt, error)
	GetQuestionBuyIn(ctx context.Context, id uuid.UUID) (pgtype.Numeric, error)
	GetUserBalanceForUpdate(ctx context.Context, id uuid.UUID) (pgtype.Numeric, error)
	ListVisualSolutionsByQuestionID(ctx context.Context, questionID uuid.UUID) ([]VisualSolution, error)
	UpdateAttemptStatus(ctx context.Context, arg UpdateAttemptStatusParams) error
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error
	UpdateUserScore(ctx context.Context, arg UpdateUserScoreParams) error
}

var _ Querier = (*Queries)(nil)
