// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: question_management.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    id, description, title, q_type, input_format, buy_in, reward, points,
    round, constraints, output_format, sample_test_input, sample_test_output,
    explanation, bounty_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, description, title, q_type, input_format, buy_in, reward, points, round, constraints, output_format, sample_test_input, sample_test_output, explanation, bounty_active
`

type CreateQuestionParams struct {
	ID               uuid.UUID
	Description      string
	Title            string
	QType            string
	InputFormat      []string
	BuyIn            pgtype.Numeric
	Reward           pgtype.Numeric
	Points           int32
	Round            int32
	Constraints      []string
	OutputFormat     []string
	SampleTestInput  []string
	SampleTestOutput []string
	Explanation      []string
	BountyActive     bool
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.ID,
		arg.Description,
		arg.Title,
		arg.QType,
		arg.InputFormat,
		arg.BuyIn,
		arg.Reward,
		arg.Points,
		arg.Round,
		arg.Constraints,
		arg.OutputFormat,
		arg.SampleTestInput,
		arg.SampleTestOutput,
		arg.Explanation,
		arg.BountyActive,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Title,
		&i.QType,
		&i.InputFormat,
		&i.BuyIn,
		&i.Reward,
		&i.Points,
		&i.Round,
		&i.Constraints,
		&i.OutputFormat,
		&i.SampleTestInput,
		&i.SampleTestOutput,
		&i.Explanation,
		&i.BountyActive,
	)
	return i, err
}

const deleteQuestion = `-- name: DeleteQuestion :one
DELETE FROM questions WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteQuestion, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getQuestionForUser = `-- name: GetQuestionForUser :one
SELECT q.id, q.description, q.title, q.q_type, q.input_format,
       COALESCE(q.buy_in::text, ''::text) AS buy_in,
       COALESCE(q.reward::text, ''::text) AS reward, q.points, q.round,
       q.constraints, q.output_format, q.sample_test_input, q.sample_test_output,
       q.explanation, q.bounty_active
FROM questions q
JOIN users u ON u.id = $2
WHERE q.id = $1 AND q.round = u.round_qualified
`

type GetQuestionForUserParams struct {
	ID   uuid.UUID
	ID_2 uuid.UUID
}

type GetQuestionForUserRow struct {
	ID               uuid.UUID
	Description      string
	Title            string
	QType            string
	InputFormat      []string
	BuyIn            interface{}
	Reward           interface{}
	Points           int32
	Round            int32
	Constraints      []string
	OutputFormat     []string
	SampleTestInput  []string
	SampleTestOutput []string
	Explanation      []string
	BountyActive     bool
}

func (q *Queries) GetQuestionForUser(ctx context.Context, arg GetQuestionForUserParams) (GetQuestionForUserRow, error) {
	row := q.db.QueryRow(ctx, getQuestionForUser, arg.ID, arg.ID_2)
	var i GetQuestionForUserRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Title,
		&i.QType,
		&i.InputFormat,
		&i.BuyIn,
		&i.Reward,
		&i.Points,
		&i.Round,
		&i.Constraints,
		&i.OutputFormat,
		&i.SampleTestInput,
		&i.SampleTestOutput,
		&i.Explanation,
		&i.BountyActive,
	)
	return i, err
}

const setQuestionBountyActive = `-- name: SetQuestionBountyActive :one
UPDATE questions SET bounty_active = $2 WHERE id = $1 RETURNING id, description, title, q_type, input_format, buy_in, reward, points, round, constraints, output_format, sample_test_input, sample_test_output, explanation, bounty_active
`

type SetQuestionBountyActiveParams struct {
	ID           uuid.UUID
	BountyActive bool
}

func (q *Queries) SetQuestionBountyActive(ctx context.Context, arg SetQuestionBountyActiveParams) (Question, error) {
	row := q.db.QueryRow(ctx, setQuestionBountyActive, arg.ID, arg.BountyActive)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Title,
		&i.QType,
		&i.InputFormat,
		&i.BuyIn,
		&i.Reward,
		&i.Points,
		&i.Round,
		&i.Constraints,
		&i.OutputFormat,
		&i.SampleTestInput,
		&i.SampleTestOutput,
		&i.Explanation,
		&i.BountyActive,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET description = $2, title = $3, q_type = $4, input_format = $5,
    buy_in = $6, reward = $7, points = $8, round = $9, constraints = $10,
    output_format = $11, sample_test_input = $12, sample_test_output = $13,
    explanation = $14, bounty_active = $15
WHERE id = $1
RETURNING id, description, title, q_type, input_format, buy_in, reward, points, round, constraints, output_format, sample_test_input, sample_test_output, explanation, bounty_active
`

type UpdateQuestionParams struct {
	ID               uuid.UUID
	Description      string
	Title            string
	QType            string
	InputFormat      []string
	BuyIn            pgtype.Numeric
	Reward           pgtype.Numeric
	Points           int32
	Round            int32
	Constraints      []string
	OutputFormat     []string
	SampleTestInput  []string
	SampleTestOutput []string
	Explanation      []string
	BountyActive     bool
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, updateQuestion,
		arg.ID,
		arg.Description,
		arg.Title,
		arg.QType,
		arg.InputFormat,
		arg.BuyIn,
		arg.Reward,
		arg.Points,
		arg.Round,
		arg.Constraints,
		arg.OutputFormat,
		arg.SampleTestInput,
		arg.SampleTestOutput,
		arg.Explanation,
		arg.BountyActive,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Title,
		&i.QType,
		&i.InputFormat,
		&i.BuyIn,
		&i.Reward,
		&i.Points,
		&i.Round,
		&i.Constraints,
		&i.OutputFormat,
		&i.SampleTestInput,
		&i.SampleTestOutput,
		&i.Explanation,
		&i.BountyActive,
	)
	return i, err
}
