// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: round1_questions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT
    id,
    description,
    title,
    q_type,
    input_format,
    COALESCE(buy_in::text, ''::text) AS buy_in,
    COALESCE(reward::text, ''::text) AS reward,
    points,
    round,
    constraints,
    output_format,
    sample_test_input,
    sample_test_output,
    explanation
FROM questions
WHERE id = $1
`

type GetQuestionByIDRow struct {
	ID               uuid.UUID
	Description      string
	Title            string
	QType            string
	InputFormat      []string
	BuyIn            interface{}
	Reward           interface{}
	Points           int32
	Round            int32
	Constraints      []string
	OutputFormat     []string
	SampleTestInput  []string
	SampleTestOutput []string
	Explanation      []string
}

func (q *Queries) GetQuestionByID(ctx context.Context, id uuid.UUID) (GetQuestionByIDRow, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i GetQuestionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Title,
		&i.QType,
		&i.InputFormat,
		&i.BuyIn,
		&i.Reward,
		&i.Points,
		&i.Round,
		&i.Constraints,
		&i.OutputFormat,
		&i.SampleTestInput,
		&i.SampleTestOutput,
		&i.Explanation,
	)
	return i, err
}

const getRoundOneVisualQuestion = `-- name: GetRoundOneVisualQuestion :one
SELECT id
FROM questions
WHERE id = $1
  AND round = 1
  AND LOWER(q_type) = 'visual'
`

func (q *Queries) GetRoundOneVisualQuestion(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRoundOneVisualQuestion, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const listQuestionsByRound = `-- name: ListQuestionsByRound :many
SELECT
    id,
    description,
    title,
    q_type,
    input_format,
    COALESCE(buy_in::text, ''::text) AS buy_in,
    COALESCE(reward::text, ''::text) AS reward,
    points,
    round,
    constraints,
    output_format,
    sample_test_input,
    sample_test_output,
    explanation
FROM questions
WHERE round = $1
ORDER BY title ASC, id ASC
`

type ListQuestionsByRoundRow struct {
	ID               uuid.UUID
	Description      string
	Title            string
	QType            string
	InputFormat      []string
	BuyIn            interface{}
	Reward           interface{}
	Points           int32
	Round            int32
	Constraints      []string
	OutputFormat     []string
	SampleTestInput  []string
	SampleTestOutput []string
	Explanation      []string
}

func (q *Queries) ListQuestionsByRound(ctx context.Context, round int32) ([]ListQuestionsByRoundRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsByRound, round)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsByRoundRow
	for rows.Next() {
		var i ListQuestionsByRoundRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Title,
			&i.QType,
			&i.InputFormat,
			&i.BuyIn,
			&i.Reward,
			&i.Points,
			&i.Round,
			&i.Constraints,
			&i.OutputFormat,
			&i.SampleTestInput,
			&i.SampleTestOutput,
			&i.Explanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisualBlocksByQuestionID = `-- name: ListVisualBlocksByQuestionID :many
SELECT id, question_id, content
FROM visual_blocks
WHERE question_id = $1
ORDER BY id ASC
`

func (q *Queries) ListVisualBlocksByQuestionID(ctx context.Context, questionID uuid.UUID) ([]VisualBlock, error) {
	rows, err := q.db.Query(ctx, listVisualBlocksByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisualBlock
	for rows.Next() {
		var i VisualBlock
		if err := rows.Scan(&i.ID, &i.QuestionID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
