// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: round1_questions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getRoundOneVisualQuestion = `-- name: GetRoundOneVisualQuestion :one

SELECT id
FROM questions
WHERE id = $1
  AND round = 1
  AND LOWER(q_type) = 'visual'
`

// this query is already there in vihaan's pr just making it here to use it for the submit sequence
func (q *Queries) GetRoundOneVisualQuestion(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRoundOneVisualQuestion, id)
	err := row.Scan(&id)
	return id, err
}

const listVisualBlocksByQuestionID = `-- name: ListVisualBlocksByQuestionID :many
SELECT id, question_id, content
FROM visual_blocks
WHERE question_id = $1
ORDER BY id ASC
`

func (q *Queries) ListVisualBlocksByQuestionID(ctx context.Context, questionID uuid.UUID) ([]VisualBlock, error) {
	rows, err := q.db.Query(ctx, listVisualBlocksByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisualBlock
	for rows.Next() {
		var i VisualBlock
		if err := rows.Scan(&i.ID, &i.QuestionID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
