// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submission.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :exec
INSERT INTO submissions (
	id,
	question_id,
	runtime,
	source_code,
	language_id,
	description,
	memory,
	user_id,
	status
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateSubmissionParams struct {
	ID          uuid.UUID
	QuestionID  uuid.UUID
	Runtime     pgtype.Numeric
	SourceCode  string
	LanguageID  int32
	Description *string
	Memory      pgtype.Numeric
	UserID      uuid.UUID
	Status      *string
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) error {
	_, err := q.db.Exec(ctx, createSubmission,
		arg.ID,
		arg.QuestionID,
		arg.Runtime,
		arg.SourceCode,
		arg.LanguageID,
		arg.Description,
		arg.Memory,
		arg.UserID,
		arg.Status,
	)
	return err
}

const deleteSubmission = `-- name: DeleteSubmission :exec
DELETE FROM submissions
WHERE id = $1
`

func (q *Queries) DeleteSubmission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubmission, id)
	return err
}

const getBestScoreForQuestion = `-- name: GetBestScoreForQuestion :one
SELECT (
	COALESCE(
		MAX(
			(
				COALESCE(testcases_passed, 0)::numeric /
				NULLIF(
					(COALESCE(testcases_passed, 0) + COALESCE(testcases_failed, 0))::numeric,
					0::numeric
				)
			) * questions.points::numeric
		),
		0::numeric
	)
)::numeric AS best_score
FROM submissions
JOIN questions ON submissions.question_id = questions.id
WHERE submissions.user_id = $1
  AND submissions.question_id = $2
  AND submissions.id != $3
`

type GetBestScoreForQuestionParams struct {
	UserID     uuid.UUID
	QuestionID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) GetBestScoreForQuestion(ctx context.Context, arg GetBestScoreForQuestionParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getBestScoreForQuestion, arg.UserID, arg.QuestionID, arg.ID)
	var best_score pgtype.Numeric
	err := row.Scan(&best_score)
	return best_score, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, question_id, testcases_passed, testcases_failed, runtime, submission_time, source_code, language_id, description, memory, user_id, status FROM submissions
WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.TestcasesPassed,
		&i.TestcasesFailed,
		&i.Runtime,
		&i.SubmissionTime,
		&i.SourceCode,
		&i.LanguageID,
		&i.Description,
		&i.Memory,
		&i.UserID,
		&i.Status,
	)
	return i, err
}

const getSubmissionForUpdate = `-- name: GetSubmissionForUpdate :one
SELECT id, question_id, testcases_passed, testcases_failed, runtime, submission_time, source_code, language_id, description, memory, user_id, status FROM submissions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetSubmissionForUpdate(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionForUpdate, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.TestcasesPassed,
		&i.TestcasesFailed,
		&i.Runtime,
		&i.SubmissionTime,
		&i.SourceCode,
		&i.LanguageID,
		&i.Description,
		&i.Memory,
		&i.UserID,
		&i.Status,
	)
	return i, err
}
