// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submission.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :exec
INSERT INTO submissions (
	id,
	question_id,
	testcases_passed,
	testcases_failed,
	runtime,
	submission_time,
	source_code,
	language_id,
	description,
	memory,
	user_id,
	status
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
`

type CreateSubmissionParams struct {
	ID              uuid.UUID
	QuestionID      uuid.UUID
	TestcasesPassed *int32
	TestcasesFailed *int32
	Runtime         pgtype.Numeric
	SubmissionTime  pgtype.Timestamptz
	SourceCode      string
	LanguageID      int32
	Description     *string
	Memory          pgtype.Numeric
	UserID          uuid.UUID
	Status          *string
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) error {
	_, err := q.db.Exec(ctx, createSubmission,
		arg.ID,
		arg.QuestionID,
		arg.TestcasesPassed,
		arg.TestcasesFailed,
		arg.Runtime,
		arg.SubmissionTime,
		arg.SourceCode,
		arg.LanguageID,
		arg.Description,
		arg.Memory,
		arg.UserID,
		arg.Status,
	)
	return err
}
