// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submission.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :exec
INSERT INTO submissions (
	id,
	question_id,
	runtime,
	source_code,
	language_id,
	description,
	memory,
	user_id,
	status
) VALUES (
	$1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateSubmissionParams struct {
	ID          uuid.UUID
	QuestionID  uuid.UUID
	Runtime     pgtype.Numeric
	SourceCode  string
	LanguageID  int32
	Description *string
	Memory      pgtype.Numeric
	UserID      uuid.UUID
	Status      *string
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) error {
	_, err := q.db.Exec(ctx, createSubmission,
		arg.ID,
		arg.QuestionID,
		arg.Runtime,
		arg.SourceCode,
		arg.LanguageID,
		arg.Description,
		arg.Memory,
		arg.UserID,
		arg.Status,
	)
	return err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, question_id, testcases_passed, testcases_failed, runtime, submission_time, source_code, language_id, description, memory, user_id, status FROM submissions
WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.TestcasesPassed,
		&i.TestcasesFailed,
		&i.Runtime,
		&i.SubmissionTime,
		&i.SourceCode,
		&i.LanguageID,
		&i.Description,
		&i.Memory,
		&i.UserID,
		&i.Status,
	)
	return i, err
}

const getSubmissionStatusByID = `-- name: GetSubmissionStatusByID :one
SELECT status FROM submissions
WHERE id = $1
`

func (q *Queries) GetSubmissionStatusByID(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getSubmissionStatusByID, id)
	var status *string
	err := row.Scan(&status)
	return status, err
}
