// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: testcases.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTestCase = `-- name: CreateTestCase :one
INSERT INTO testcases (
    id,
    expected_output,
    memory,
    input,
    hidden,
    runtime,
    question_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, expected_output, memory, input, hidden, runtime, question_id
`

type CreateTestCaseParams struct {
	ID             uuid.UUID
	ExpectedOutput string
	Memory         pgtype.Numeric
	Input          string
	Hidden         bool
	Runtime        pgtype.Numeric
	QuestionID     uuid.UUID
}

func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (Testcase, error) {
	row := q.db.QueryRow(ctx, createTestCase,
		arg.ID,
		arg.ExpectedOutput,
		arg.Memory,
		arg.Input,
		arg.Hidden,
		arg.Runtime,
		arg.QuestionID,
	)
	var i Testcase
	err := row.Scan(
		&i.ID,
		&i.ExpectedOutput,
		&i.Memory,
		&i.Input,
		&i.Hidden,
		&i.Runtime,
		&i.QuestionID,
	)
	return i, err
}

const getAllTestCasesByQuestion = `-- name: GetAllTestCasesByQuestion :many
SELECT
    id,
    memory,
    expected_output,
    input,
    hidden,
    runtime,
    question_id
FROM testcases
WHERE question_id = $1
`

type GetAllTestCasesByQuestionRow struct {
	ID             uuid.UUID
	Memory         pgtype.Numeric
	ExpectedOutput string
	Input          string
	Hidden         bool
	Runtime        pgtype.Numeric
	QuestionID     uuid.UUID
}

func (q *Queries) GetAllTestCasesByQuestion(ctx context.Context, questionID uuid.UUID) ([]GetAllTestCasesByQuestionRow, error) {
	rows, err := q.db.Query(ctx, getAllTestCasesByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTestCasesByQuestionRow
	for rows.Next() {
		var i GetAllTestCasesByQuestionRow
		if err := rows.Scan(
			&i.ID,
			&i.Memory,
			&i.ExpectedOutput,
			&i.Input,
			&i.Hidden,
			&i.Runtime,
			&i.QuestionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
