// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: visual_submissions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVisualSolution = `-- name: CreateVisualSolution :one
INSERT INTO visual_solutions (id, question_id, solution, points)
VALUES ($1, $2, $3, $4)
RETURNING id, question_id, solution, points
`

type CreateVisualSolutionParams struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	Solution   []uuid.UUID
	Points     pgtype.Numeric
}

func (q *Queries) CreateVisualSolution(ctx context.Context, arg CreateVisualSolutionParams) (VisualSolution, error) {
	row := q.db.QueryRow(ctx, createVisualSolution,
		arg.ID,
		arg.QuestionID,
		arg.Solution,
		arg.Points,
	)
	var i VisualSolution
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Solution,
		&i.Points,
	)
	return i, err
}

const createVisualSubmission = `-- name: CreateVisualSubmission :one
INSERT INTO submissions(
    id,
    question_id,
    source_code,
    language_id,
    user_id,
    status
)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, question_id, testcases_passed, testcases_failed, runtime, submission_time, source_code, language_id, description, memory, user_id, status
`

type CreateVisualSubmissionParams struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	SourceCode string
	LanguageID int32
	UserID     uuid.UUID
	Status     *string
}

func (q *Queries) CreateVisualSubmission(ctx context.Context, arg CreateVisualSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createVisualSubmission,
		arg.ID,
		arg.QuestionID,
		arg.SourceCode,
		arg.LanguageID,
		arg.UserID,
		arg.Status,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.TestcasesPassed,
		&i.TestcasesFailed,
		&i.Runtime,
		&i.SubmissionTime,
		&i.SourceCode,
		&i.LanguageID,
		&i.Description,
		&i.Memory,
		&i.UserID,
		&i.Status,
	)
	return i, err
}

const deleteVisualSolution = `-- name: DeleteVisualSolution :exec
DELETE FROM visual_solutions WHERE id = $1
`

func (q *Queries) DeleteVisualSolution(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVisualSolution, id)
	return err
}

const deleteVisualSolutionsByQuestionID = `-- name: DeleteVisualSolutionsByQuestionID :exec
DELETE FROM visual_solutions WHERE question_id = $1
`

func (q *Queries) DeleteVisualSolutionsByQuestionID(ctx context.Context, questionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVisualSolutionsByQuestionID, questionID)
	return err
}

const getQuestionReward = `-- name: GetQuestionReward :one
SELECT reward
FROM questions
WHERE id = $1
`

func (q *Queries) GetQuestionReward(ctx context.Context, id uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getQuestionReward, id)
	var reward pgtype.Numeric
	err := row.Scan(&reward)
	return reward, err
}

const getUserScoreForUpdate = `-- name: GetUserScoreForUpdate :one
SELECT score
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetUserScoreForUpdate(ctx context.Context, id uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getUserScoreForUpdate, id)
	var score pgtype.Numeric
	err := row.Scan(&score)
	return score, err
}

const listVisualSolutionsByQuestionID = `-- name: ListVisualSolutionsByQuestionID :many
SELECT id,question_id,solution,points
FROM visual_solutions
WHERE question_id = $1
`

func (q *Queries) ListVisualSolutionsByQuestionID(ctx context.Context, questionID uuid.UUID) ([]VisualSolution, error) {
	rows, err := q.db.Query(ctx, listVisualSolutionsByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisualSolution
	for rows.Next() {
		var i VisualSolution
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Solution,
			&i.Points,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttemptStatus = `-- name: UpdateAttemptStatus :exec
UPDATE attempts
SET
    status = $3,
    answered_at = $4
WHERE user_id = $1
  AND question_id = $2
`

type UpdateAttemptStatusParams struct {
	UserID     uuid.UUID
	QuestionID uuid.UUID
	Status     string
	AnsweredAt pgtype.Timestamptz
}

func (q *Queries) UpdateAttemptStatus(ctx context.Context, arg UpdateAttemptStatusParams) error {
	_, err := q.db.Exec(ctx, updateAttemptStatus,
		arg.UserID,
		arg.QuestionID,
		arg.Status,
		arg.AnsweredAt,
	)
	return err
}

const updateUserScore = `-- name: UpdateUserScore :exec
UPDATE users
SET score = $2
WHERE id = $1
`

type UpdateUserScoreParams struct {
	ID    uuid.UUID
	Score pgtype.Numeric
}

func (q *Queries) UpdateUserScore(ctx context.Context, arg UpdateUserScoreParams) error {
	_, err := q.db.Exec(ctx, updateUserScore, arg.ID, arg.Score)
	return err
}
