// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetQuestionByID(ctx context.Context, id uuid.UUID) (GetQuestionByIDRow, error)
	GetRoundOneVisualQuestion(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	ListQuestionsByRound(ctx context.Context, round int32) ([]ListQuestionsByRoundRow, error)
	ListVisualBlocksByQuestionID(ctx context.Context, questionID uuid.UUID) ([]VisualBlock, error)
}

var _ Querier = (*Queries)(nil)
